# .bashrc
function func_color_search(){
	find ~/.dircolors-solarized -maxdepth 1 -name "dircolors.*"
}

function func_color_change(){
	if [[ $# -lt 1 ]]; then
		func_color_search | while read f; do basename $f; done \
			| awk 'BEGIN{i=1;}{printf("%d : %s\n", i, $1);i++}'
		echo -n "color-idx: "
		read i
	else
		i=$1
	fi
	color_cmd=`func_color_search | awk 'BEGIN{i=1;}{if(i=="'$i'"){printf("dircolors -b %s", $1);exit 0;};i++}'`
	eval `$color_cmd`
}

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'
alias color-change='func_color_change'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#default color option-2
func_color_change 2

